version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
 
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  book:
    build:
      context: ./books
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

volumes:
         mongo-data:
networks:
         test-network: