version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    depends_on:
      - "mongo"

  mongo:
    container_name: "mongo-user"
    platform: linux/amd64
    image: mongo:4.4.14
    ports:
      - 27017:27017
networks:
  backend:
    driver: bridge
